version: "2"

services:
  app:
    build: ./app
    ports: 
      - "8080:8080"
    links:
      - db:db
      - cache:cache
      - log:log
  db:
   image: mysql:latest
   ports:
      - "3306:3306"
   volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
   environment:
      MYSQL_ROOT_PASSWORD: vrcc
      MYSQL_DATABASE: vrcc
      MYSQL_USER: vrcc
      MYSQL_PASSWORD: vrcc
  cache:
   image: redis:alpine
   ports:
      - "6379:6379"
  log:
   image: pblittle/docker-logstash
   ports:
      - "9292:9292"
      - "9200:9200"
      - "9998:9998"
      - "9999:9999/udp"
   volumes:
      - ./log/logstash-embedded.conf:/opt/logstash/conf.d/logstash-embedded.conf
